CREATE TABLE HistoryOrders (
    Id INT PRIMARY KEY IDENTITY(1,1),
    OrderId NVARCHAR(50),
    UserId NVARCHAR(50),
    UserEmail NVARCHAR(256),
    UserFirstName NVARCHAR(100),
    UserLastName NVARCHAR(100),
    UserPhoneNumber NVARCHAR(20),

    BillingCountry NVARCHAR(100),
    BillingState NVARCHAR(100),
    BillingCity NVARCHAR(100),
    BillingPostalCode NVARCHAR(20),
    BillingAddressLine NVARCHAR(200),
    BillingFirstName NVARCHAR(100),
    BillingLastName NVARCHAR(100),
    BillingPhoneNumber NVARCHAR(20),

    ShippingCountry NVARCHAR(100),
    ShippingState NVARCHAR(100),
    ShippingCity NVARCHAR(100),
    ShippingPostalCode NVARCHAR(20),
    ShippingAddressLine NVARCHAR(200),
    ShippingFirstName NVARCHAR(100),
    ShippingLastName NVARCHAR(100),
    ShippingPhoneNumber NVARCHAR(20),

    OrderStatus NVARCHAR(50),
    OrderPlacedDate DATETIME,
    OrderShippedDate DATETIME,
    OrderDeliveredDate DATETIME,
    OrderCanceledDate DATETIME,
    TotalAmount DECIMAL(18,2),
    PaymentMethod NVARCHAR(100),
    CreatedDate DATETIME DEFAULT GETDATE());
